import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  routes: [
    {
      pageName: "home-page",
      url: "",
      text: "Home",
      navLink: false,
    },

    { pageName: "log-in", url: "log-in", text: "Log in", navLink: false },
    { pageName: "sign-in", url: "sign-in", text: "Sign in", navLink: false },
    { pageName: "profile", url: "profile", text: "Profile", navLink: false },
    {
      pageName: "profile-photos",
      url: "profile/photos",
      text: "Photos",
      navLink: false,
    },
    {
      pageName: "profile-reviews",
      url: "profile/reviews",
      text: "Reviews",
      navLink: false,
    },
    {
      pageName: "profile-wishes",
      url: "profile/wishes",
      text: "Wishes",
      navLink: false,
    },
  ],
  detailPages: [
    {
      Id: 5,
      EntityId: 2,
      EntityName: "SkiResort",
      Slug: "uludag-kayak-merkezi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 6,
      EntityId: 2,
      EntityName: "SkiResort",
      Slug: "uludag-kayak-merkezi",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 7,
      EntityId: 2,
      EntityName: "SkiResort",
      Slug: "uludag-ski-center",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 8,
      EntityId: 3,
      EntityName: "SkiResort",
      Slug: "erciyes-kayak-merkezi",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 9,
      EntityId: 3,
      EntityName: "SkiResort",
      Slug: "erciyes-kayak-merkezi",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 10,
      EntityId: 3,
      EntityName: "SkiResort",
      Slug: "erciyes-kayak-merkezi",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 11,
      EntityId: 4,
      EntityName: "SkiResort",
      Slug: "kartalkaya-kayak-merkezi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 12,
      EntityId: 5,
      EntityName: "SkiResort",
      Slug: "palandoken-kayak-merkezi",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 13,
      EntityId: 6,
      EntityName: "SkiResort",
      Slug: "sarıkamış-kayak-merkezi",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 14,
      EntityId: 1,
      EntityName: "Hotel",
      Slug: "grand-kartal-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 15,
      EntityId: 2,
      EntityName: "Hotel",
      Slug: "kartal-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 16,
      EntityId: 3,
      EntityName: "Hotel",
      Slug: "dorukkaya-otel",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 17,
      EntityId: 4,
      EntityName: "Hotel",
      Slug: "kartalkaya-kaya-palazzo",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 18,
      EntityId: 5,
      EntityName: "Hotel",
      Slug: "golden-key-kartalkaya",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 24,
      EntityId: 1,
      EntityName: "SkiSchool",
      Slug: "the-champions-team",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 27,
      EntityId: 7,
      EntityName: "Hotel",
      Slug: "grand-yazıcı-uludag",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 29,
      EntityId: 1,
      EntityName: "Restaurant",
      Slug: "restoran-1",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 30,
      EntityId: 8,
      EntityName: "Hotel",
      Slug: "bof-hotel-uludag",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 31,
      EntityId: 9,
      EntityName: "Hotel",
      Slug: "mirada-del-lago-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 32,
      EntityId: 10,
      EntityName: "Hotel",
      Slug: "radisson-blu-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 33,
      EntityId: 11,
      EntityName: "Hotel",
      Slug: "snowdora-hotel-palandoken",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 34,
      EntityId: 12,
      EntityName: "Hotel",
      Slug: "palan-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 35,
      EntityId: 13,
      EntityName: "Hotel",
      Slug: "dedeman-palandoken-hotel",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 36,
      EntityId: 14,
      EntityName: "Hotel",
      Slug: "sway-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 37,
      EntityId: 15,
      EntityName: "Hotel",
      Slug: "sarıkamış-kayı-resort-hotel",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 38,
      EntityId: 16,
      EntityName: "Hotel",
      Slug: "ekinata-grand-toprak-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 44,
      EntityId: 5,
      EntityName: "SkiResort",
      Slug: "palandoken-kayak-merkezi",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 45,
      EntityId: 5,
      EntityName: "SkiResort",
      Slug: "palandoken-ski-resort",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 46,
      EntityId: 6,
      EntityName: "SkiResort",
      Slug: "sarıkamış-kayak-merkezi",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 47,
      EntityId: 6,
      EntityName: "SkiResort",
      Slug: "sarıkamış-ski-resort",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 48,
      EntityId: 4,
      EntityName: "SkiResort",
      Slug: "kartalkaya-kayak-merkezi",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 49,
      EntityId: 4,
      EntityName: "SkiResort",
      Slug: "kartalkaya-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 51,
      EntityId: 1,
      EntityName: "Activity",
      Slug: "kayak-ve-snowboard-eğitimi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 52,
      EntityId: 2,
      EntityName: "SkiSchool",
      Slug: "deneme-okul",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 1024,
      EntityId: 1,
      EntityName: "Page",
      Slug: "ana-sayfa",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 1025,
      EntityId: 1002,
      EntityName: "SkiSchool",
      Slug: "palan-ski-school",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 1026,
      EntityId: 2,
      EntityName: "Activity",
      Slug: "kayak-dersİ",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2024,
      EntityId: 1,
      EntityName: "Page",
      Slug: "ana-sayfa",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 2025,
      EntityId: 1,
      EntityName: "Page",
      Slug: "home-page",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 2026,
      EntityId: 2,
      EntityName: "Page",
      Slug: "ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2027,
      EntityId: 3,
      EntityName: "Page",
      Slug: "hotels",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2028,
      EntityId: 4,
      EntityName: "Page",
      Slug: "food-beverage",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2029,
      EntityId: 5,
      EntityName: "Page",
      Slug: "tours",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2030,
      EntityId: 6,
      EntityName: "Page",
      Slug: "ski-school",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2031,
      EntityId: 1,
      EntityName: "Page",
      Slug: "home-page",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2032,
      EntityId: 1002,
      EntityName: "SkiSchool",
      Slug: "palandöken-kayak-okulu",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 2033,
      EntityId: 1002,
      EntityName: "SkiSchool",
      Slug: "palandoken-ski-school",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 2034,
      EntityId: 2,
      EntityName: "Page",
      Slug: "kayak-merkezleri",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 2035,
      EntityId: 6,
      EntityName: "Page",
      Slug: "kayak-okulları",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 2036,
      EntityId: 3,
      EntityName: "Page",
      Slug: "oteller",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 2037,
      EntityId: 4,
      EntityName: "Page",
      Slug: "yiyecek-İçecek",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 2038,
      EntityId: 5,
      EntityName: "Page",
      Slug: "turlar",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 2039,
      EntityId: 6,
      EntityName: "SkiResort",
      Slug: "sarikamis-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2040,
      EntityId: 3,
      EntityName: "SkiResort",
      Slug: "erciyes-ski-resort-turkey",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 2041,
      EntityId: 6,
      EntityName: "SkiResort",
      Slug: "sarikamis-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 2042,
      EntityId: 1013,
      EntityName: "SkiResort",
      Slug: "ovit-dağı",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 2043,
      EntityId: 1007,
      EntityName: "Hotel",
      Slug: "2640-butik-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2044,
      EntityId: 1003,
      EntityName: "SkiSchool",
      Slug: "ovit",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 2048,
      EntityId: 1003,
      EntityName: "SkiSchool",
      Slug: "ovit-ski-school",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2049,
      EntityId: 1002,
      EntityName: "Activity",
      Slug: "unlimited-daily-freeride-ski-trips",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2050,
      EntityId: 1002,
      EntityName: "Activity",
      Slug: "sınırsız-günlük-freeride-kayak-gezileri",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 2051,
      EntityId: 1002,
      EntityName: "Activity",
      Slug: "unlimited-daily-freeride-ski-trips",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 2053,
      EntityId: 1003,
      EntityName: "Activity",
      Slug: "unlimited-half-day-freeride-ski-trips",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 2054,
      EntityId: 1003,
      EntityName: "Activity",
      Slug: "sınırsız-yarım-gün-freeride-kayak-gezileri",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 2055,
      EntityId: 1003,
      EntityName: "Activity",
      Slug: "unlimited-half-day-freeride-ski-trips",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 3042,
      EntityId: 1013,
      EntityName: "SkiResort",
      Slug: "ovit-mountain",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 3043,
      EntityId: 1013,
      EntityName: "SkiResort",
      Slug: "ovit-mountain",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 3044,
      EntityId: 1007,
      EntityName: "Hotel",
      Slug: "2640-boutique-hotel",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 3045,
      EntityId: 1061,
      EntityName: "Room",
      Slug: "2640-butik-otel-suite-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 3046,
      EntityId: 1060,
      EntityName: "Room",
      Slug: "2640-butik-otel-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 3048,
      EntityId: 1059,
      EntityName: "Room",
      Slug: "2640-butik-otel-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 3049,
      EntityId: 2002,
      EntityName: "Activity",
      Slug: "unlimited-drops-snowmobile-shuttles",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 3050,
      EntityId: 8,
      EntityName: "Restaurant",
      Slug: "ovit-restaurant",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4050,
      EntityId: 1,
      EntityName: "Hotel",
      Slug: "grand-kartal-main-restaurant",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4051,
      EntityId: 9,
      EntityName: "Hotel",
      Slug: "mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4052,
      EntityId: 1025,
      EntityName: "Room",
      Slug: "double-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4053,
      EntityId: 1025,
      EntityName: "Room",
      Slug: "mirada-del-lago-2-kisilik-oda",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4054,
      EntityId: 1025,
      EntityName: "Room",
      Slug: "double-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4055,
      EntityId: 1026,
      EntityName: "Room",
      Slug: "trible-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4056,
      EntityId: 1026,
      EntityName: "Room",
      Slug: "3-kisilik-oda-5",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4057,
      EntityId: 1026,
      EntityName: "Room",
      Slug: "trible-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4058,
      EntityId: 1027,
      EntityName: "Room",
      Slug: "single-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4059,
      EntityId: 1027,
      EntityName: "Room",
      Slug: "tek-kisilik-oda-6",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4060,
      EntityId: 1027,
      EntityName: "Room",
      Slug: "single-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4061,
      EntityId: 1028,
      EntityName: "Room",
      Slug: "suite-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4062,
      EntityId: 1028,
      EntityName: "Room",
      Slug: "suit-oda-short",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4063,
      EntityId: 1029,
      EntityName: "Room",
      Slug: "family-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4064,
      EntityId: 1029,
      EntityName: "Room",
      Slug: "family-room-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4065,
      EntityId: 1030,
      EntityName: "Room",
      Slug: "mirada-del-lago-otel-room-for-disabled",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4066,
      EntityId: 1030,
      EntityName: "Room",
      Slug: "engelli-oda",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4067,
      EntityId: 1030,
      EntityName: "Room",
      Slug: "room-for-disabled-mirada-del-lago-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4068,
      EntityId: 1031,
      EntityName: "Room",
      Slug: "grand-family",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4069,
      EntityId: 1031,
      EntityName: "Room",
      Slug: "grand-family-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4070,
      EntityId: 1032,
      EntityName: "Room",
      Slug: "mirada-del-lago-otel-grand-suite-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4071,
      EntityId: 1032,
      EntityName: "Room",
      Slug: "grand-suite",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4072,
      EntityId: 1033,
      EntityName: "Room",
      Slug: "mirada-del-lago-otel-king-suite-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4073,
      EntityId: 1033,
      EntityName: "Room",
      Slug: "king-suite-short",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4074,
      EntityId: 1033,
      EntityName: "Room",
      Slug: "king-suite-mirada-del-lago-hotel-erciyes-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4075,
      EntityId: 1002,
      EntityName: "Restaurant",
      Slug: "radisson-blu-ana-restaurant",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4076,
      EntityId: 1002,
      EntityName: "Restaurant",
      Slug: "main-restauran",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4077,
      EntityId: 1003,
      EntityName: "Restaurant",
      Slug: "patisera",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4078,
      EntityId: 1004,
      EntityName: "Restaurant",
      Slug: "patisera-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4079,
      EntityId: 1032,
      EntityName: "Room",
      Slug: "grand-suit-mirada-del-lago-hotel",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4080,
      EntityId: 1004,
      EntityName: "Restaurant",
      Slug: "patisera-2",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4081,
      EntityId: 1005,
      EntityName: "Restaurant",
      Slug: "roof-restaurant",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4082,
      EntityId: 1005,
      EntityName: "Restaurant",
      Slug: "roof-lounge",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4083,
      EntityId: 11,
      EntityName: "Hotel",
      Slug: "snowdora-hotel-palandoken-ejder-3200",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4084,
      EntityId: 1002,
      EntityName: "Room",
      Slug: "standart-oda-snowdora-palandoken",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4085,
      EntityId: 1003,
      EntityName: "Room",
      Slug: "palandoken-chalete",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4086,
      EntityId: 12,
      EntityName: "Hotel",
      Slug: "palan-hotel-palandoken",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4087,
      EntityId: 1004,
      EntityName: "Room",
      Slug: "double-room-palan-hotel-palandoken",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4088,
      EntityId: 1004,
      EntityName: "Room",
      Slug: "2-kisilik-oda-palan-hotel",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4089,
      EntityId: 1004,
      EntityName: "Room",
      Slug: "double-room-palan-hotel-palandoken",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4090,
      EntityId: 1005,
      EntityName: "Room",
      Slug: "palan-hotel-3-kişilik-oda",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4091,
      EntityId: 1005,
      EntityName: "Room",
      Slug: "trible-room-palan-hotel-palandoken-ski-resort",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4092,
      EntityId: 1006,
      EntityName: "Room",
      Slug: "palan-hotel-tek-kişilik-oda",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4093,
      EntityId: 1006,
      EntityName: "Room",
      Slug: "single-room-palan-hotel-palandoken",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4094,
      EntityId: 13,
      EntityName: "Hotel",
      Slug: "dedeman-hotel-palandöken",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4095,
      EntityId: 1007,
      EntityName: "Room",
      Slug: "dedeman-palandoken-hotel-tek-kişilik-oda",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4096,
      EntityId: 1007,
      EntityName: "Room",
      Slug: "sngl-room-dedeman-palandoken-hotel",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4097,
      EntityId: 1008,
      EntityName: "Room",
      Slug: "dedeman-palandoken-hotel-2-kişilik-oda",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4098,
      EntityId: 1008,
      EntityName: "Room",
      Slug: "double-room-dedeman-palandoken-hotel",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4099,
      EntityId: 1009,
      EntityName: "Room",
      Slug: "dedeman-palandoken-hotel-3-kişilik-oda",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4100,
      EntityId: 1009,
      EntityName: "Room",
      Slug: "triple-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4101,
      EntityId: 1010,
      EntityName: "Room",
      Slug: "dedeman-palandoken-hotel-deluxe-triple-room",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4102,
      EntityId: 1010,
      EntityName: "Room",
      Slug: "deluxe-trible-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4103,
      EntityId: 1011,
      EntityName: "Room",
      Slug: "dedeman-palandoken-hotel-junior-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4104,
      EntityId: 1011,
      EntityName: "Room",
      Slug: "unior-suite",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4105,
      EntityId: 14,
      EntityName: "Hotel",
      Slug: "sway-hotel-palandoken",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4106,
      EntityId: 14,
      EntityName: "Hotel",
      Slug: "sway-hotel",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4107,
      EntityId: 1012,
      EntityName: "Room",
      Slug: "sway-hotel-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4108,
      EntityId: 1012,
      EntityName: "Room",
      Slug: "standart-room",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4109,
      EntityId: 1013,
      EntityName: "Room",
      Slug: "sway-hotel-junior-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4110,
      EntityId: 1013,
      EntityName: "Room",
      Slug: "junior-suite",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4111,
      EntityId: 1014,
      EntityName: "Room",
      Slug: "sway-hotel-deluxe-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4112,
      EntityId: 1014,
      EntityName: "Room",
      Slug: "deeluxe-room",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4113,
      EntityId: 1015,
      EntityName: "Room",
      Slug: "sway-hotel-presidental-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4114,
      EntityId: 1015,
      EntityName: "Room",
      Slug: "presidental-suite",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4115,
      EntityId: 1,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4116,
      EntityId: 2,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-family-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4117,
      EntityId: 1049,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-connection-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4118,
      EntityId: 1050,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-corner-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4119,
      EntityId: 1051,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-junior-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4120,
      EntityId: 1051,
      EntityName: "Room",
      Slug: "junior-suite-2",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4121,
      EntityId: 1052,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-king-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4122,
      EntityId: 8,
      EntityName: "Hotel",
      Slug: "bof-hotel-uludag",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4136,
      EntityId: 1053,
      EntityName: "Room",
      Slug: "bof-hotel-uludag-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4137,
      EntityId: 1053,
      EntityName: "Room",
      Slug: "tek-kişilik-oda",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4138,
      EntityId: 1053,
      EntityName: "Room",
      Slug: "single-room",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4139,
      EntityId: 1054,
      EntityName: "Room",
      Slug: "bof-hotel-uludag-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4140,
      EntityId: 1054,
      EntityName: "Room",
      Slug: "2-kişilik-oda",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4141,
      EntityId: 1054,
      EntityName: "Room",
      Slug: "standart-dbl-room",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4142,
      EntityId: 1055,
      EntityName: "Room",
      Slug: "bof-hotel-uludag-triple-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4143,
      EntityId: 1055,
      EntityName: "Room",
      Slug: "3-kişilik-oda",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4144,
      EntityId: 1055,
      EntityName: "Room",
      Slug: "standard-trible-room",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4145,
      EntityId: 1056,
      EntityName: "Room",
      Slug: "bof-hotel-uludag-junior-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4146,
      EntityId: 15,
      EntityName: "Hotel",
      Slug: "sarıkamış-kayı-resort-hotel",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4147,
      EntityId: 1008,
      EntityName: "Hotel",
      Slug: "standart-oda",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4148,
      EntityId: 1057,
      EntityName: "Room",
      Slug: "sarıkamış-kayı-resort-hotel-standart-room",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4149,
      EntityId: 16,
      EntityName: "Hotel",
      Slug: "ekinata-grand-toprak-hotel",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4150,
      EntityId: 1058,
      EntityName: "Room",
      Slug: "ekinata-grand-toprak-otel-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4151,
      EntityId: 1058,
      EntityName: "Room",
      Slug: "standart-rooms",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4152,
      EntityId: 1017,
      EntityName: "Room",
      Slug: "grand-kartal-otel-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4153,
      EntityId: 1018,
      EntityName: "Room",
      Slug: "grand-kartal-otel-triple-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4154,
      EntityId: 1018,
      EntityName: "Room",
      Slug: "trbl-rooms",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4155,
      EntityId: 1019,
      EntityName: "Room",
      Slug: "grand-kartal-otel-quart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4156,
      EntityId: 1019,
      EntityName: "Room",
      Slug: "4-kişilik-oda",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4157,
      EntityId: 1019,
      EntityName: "Room",
      Slug: "quart-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4158,
      EntityId: 1020,
      EntityName: "Room",
      Slug: "grand-kartal-otel-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4159,
      EntityId: 1020,
      EntityName: "Room",
      Slug: "tek-kişilik-oda-2",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4160,
      EntityId: 1020,
      EntityName: "Room",
      Slug: "single-room-2",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4161,
      EntityId: 1021,
      EntityName: "Room",
      Slug: "grand-kartal-otel-corner-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4162,
      EntityId: 1021,
      EntityName: "Room",
      Slug: "köşe-oda",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4163,
      EntityId: 1021,
      EntityName: "Room",
      Slug: "corner-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4164,
      EntityId: 1022,
      EntityName: "Room",
      Slug: "grand-kartal-otel-connection-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4165,
      EntityId: 1022,
      EntityName: "Room",
      Slug: "bağlantılı-oda",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4166,
      EntityId: 1022,
      EntityName: "Room",
      Slug: "connection-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4167,
      EntityId: 1023,
      EntityName: "Room",
      Slug: "grand-kartal-otel-suite-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4168,
      EntityId: 1023,
      EntityName: "Room",
      Slug: "suit-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4169,
      EntityId: 1037,
      EntityName: "Room",
      Slug: "kartal-otel-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4170,
      EntityId: 1037,
      EntityName: "Room",
      Slug: "single-room-3",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4171,
      EntityId: 1038,
      EntityName: "Room",
      Slug: "kartal-otel-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4172,
      EntityId: 1038,
      EntityName: "Room",
      Slug: "2-kişilik-oda-2",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4173,
      EntityId: 1038,
      EntityName: "Room",
      Slug: "double-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4174,
      EntityId: 1039,
      EntityName: "Room",
      Slug: "kartal-otel-triple-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4175,
      EntityId: 1039,
      EntityName: "Room",
      Slug: "3-kişilik-oda-2",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4176,
      EntityId: 1039,
      EntityName: "Room",
      Slug: "trible-room",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4177,
      EntityId: 1040,
      EntityName: "Room",
      Slug: "kartal-otel-dublex-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4178,
      EntityId: 1040,
      EntityName: "Room",
      Slug: "duplex-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4179,
      EntityId: 1041,
      EntityName: "Room",
      Slug: "kartal-otel-suite-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4180,
      EntityId: 1041,
      EntityName: "Room",
      Slug: "suite-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4181,
      EntityId: 1042,
      EntityName: "Room",
      Slug: "kartal-otel-dublex-suite-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4182,
      EntityId: 1042,
      EntityName: "Room",
      Slug: "duplex-suite-room",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4183,
      EntityId: 1043,
      EntityName: "Room",
      Slug: "kartal-otel-kartal-chalet",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4184,
      EntityId: 1043,
      EntityName: "Room",
      Slug: "kartal-chalet",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4185,
      EntityId: 3,
      EntityName: "Hotel",
      Slug: "dorukkaya-ski-resort-kartalkaya",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4186,
      EntityId: 1044,
      EntityName: "Room",
      Slug: "dorukkaya-otel-standart-room",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4187,
      EntityId: 1044,
      EntityName: "Room",
      Slug: "standart-room-dorukkaya-hotel",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4188,
      EntityId: 4,
      EntityName: "Hotel",
      Slug: "kartalkaya-palazzo-ski-resort",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4189,
      EntityId: 1045,
      EntityName: "Room",
      Slug: "kartalkaya-kaya-palazzo-deluxe-oda",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4190,
      EntityId: 1046,
      EntityName: "Room",
      Slug: "kartalkaya-kaya-palazzo-deluxe-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4191,
      EntityId: 5,
      EntityName: "Hotel",
      Slug: "golden-key-hotel-kartalkaya",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4192,
      EntityId: 1009,
      EntityName: "Hotel",
      Slug: "standart-room-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4193,
      EntityId: 1006,
      EntityName: "Restaurant",
      Slug: "grand-kartal-restaurantları",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4194,
      EntityId: 1006,
      EntityName: "Restaurant",
      Slug: "grand-kartal-main-restaurant-2",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4195,
      EntityId: 1007,
      EntityName: "Restaurant",
      Slug: "lobby-bar",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4196,
      EntityId: 1007,
      EntityName: "Restaurant",
      Slug: "lobby",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4197,
      EntityId: 1008,
      EntityName: "Restaurant",
      Slug: "café-kartal",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4198,
      EntityId: 1008,
      EntityName: "Restaurant",
      Slug: "café-kartal",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4199,
      EntityId: 1009,
      EntityName: "Restaurant",
      Slug: "doruk-café",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4200,
      EntityId: 1009,
      EntityName: "Restaurant",
      Slug: "tepe-café",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4201,
      EntityId: 1010,
      EntityName: "Restaurant",
      Slug: "american-bar",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4202,
      EntityId: 1010,
      EntityName: "Restaurant",
      Slug: "american-bar",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4203,
      EntityId: 3,
      EntityName: "Hotel",
      Slug: "dorukkaya-otel",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4204,
      EntityId: 4,
      EntityName: "Hotel",
      Slug: "kartalkaya-kaya-palazzo",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4205,
      EntityId: 5,
      EntityName: "Hotel",
      Slug: "golden-key-kartalkaya",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4206,
      EntityId: 1004,
      EntityName: "Restaurant",
      Slug: "patisera-2",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4207,
      EntityId: 1005,
      EntityName: "Restaurant",
      Slug: "roof-restaurant",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4208,
      EntityId: 1006,
      EntityName: "Restaurant",
      Slug: "grand-kartal-restaurantları",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4209,
      EntityId: 1007,
      EntityName: "Restaurant",
      Slug: "lobby-bar",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4210,
      EntityId: 1008,
      EntityName: "Restaurant",
      Slug: "café-kartal",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4211,
      EntityId: 1009,
      EntityName: "Restaurant",
      Slug: "doruk-café",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4212,
      EntityId: 1010,
      EntityName: "Restaurant",
      Slug: "american-bar",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4471,
      EntityId: 1016,
      EntityName: "Room",
      Slug: "grand-kartal-otel-grand-kartal-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4472,
      EntityId: 1016,
      EntityName: "Room",
      Slug: "grand-kartal-otel-2",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4473,
      EntityId: 1016,
      EntityName: "Room",
      Slug: "grand-kartal-hotel",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4474,
      EntityId: 1024,
      EntityName: "Room",
      Slug: "grand-kartal-otel-king-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4475,
      EntityId: 3,
      EntityName: "Room",
      Slug: "grand-kartal-otel-11",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4476,
      EntityId: 1047,
      EntityName: "Room",
      Slug: "kartalkaya-kaya-palazzo-king-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4477,
      EntityId: 1048,
      EntityName: "Room",
      Slug: "golden-key-kartalkaya-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4478,
      EntityId: 1048,
      EntityName: "Room",
      Slug: "standart-roomz",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4479,
      EntityId: 1034,
      EntityName: "Room",
      Slug: "radisson-blu-hotel-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4480,
      EntityId: 1035,
      EntityName: "Room",
      Slug: "radisson-blu-hotel-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4481,
      EntityId: 1036,
      EntityName: "Room",
      Slug: "radisson-blu-hotel-triple-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4482,
      EntityId: 7,
      EntityName: "Page",
      Slug: "deneme",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4484,
      EntityId: 1010,
      EntityName: "Hotel",
      Slug: "palan-otel-palandoken",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4485,
      EntityId: 1011,
      EntityName: "Hotel",
      Slug: "palan-otel-palandoken-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4486,
      EntityId: 1012,
      EntityName: "Hotel",
      Slug: "palan-otel-palandoken-3",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4487,
      EntityId: 1013,
      EntityName: "Hotel",
      Slug: "mirada-del-lago-otel-2",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4488,
      EntityId: 1014,
      EntityName: "Hotel",
      Slug: "radisson-blu-hotel-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4489,
      EntityId: 1015,
      EntityName: "Hotel",
      Slug: "radisson-blu-hotel-3",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4490,
      EntityId: 1016,
      EntityName: "Hotel",
      Slug: "sarıkamıs-kayı-resort-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4491,
      EntityId: 1017,
      EntityName: "Hotel",
      Slug: "sarıkamıs-kayı-resort-otel",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4492,
      EntityId: 1018,
      EntityName: "Hotel",
      Slug: "snowdora-hotel-palandoken-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4493,
      EntityId: 1019,
      EntityName: "Hotel",
      Slug: "snowdora-hotel-palandoken-3",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4494,
      EntityId: 1020,
      EntityName: "Hotel",
      Slug: "dedeman-palandoken-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4495,
      EntityId: 1021,
      EntityName: "Hotel",
      Slug: "dedeman-palandoken-otel-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4496,
      EntityId: 1022,
      EntityName: "Hotel",
      Slug: "dedeman-palandoken-otel-3",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4498,
      EntityId: 1024,
      EntityName: "Hotel",
      Slug: "sway-hotel-palandoken",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4499,
      EntityId: 1025,
      EntityName: "Hotel",
      Slug: "grand-yazıcı-uludag-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4500,
      EntityId: 1026,
      EntityName: "Hotel",
      Slug: "bof-otel-uludag",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4510,
      EntityId: 1013,
      EntityName: "SkiResort",
      Slug: "ovit-dagı",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4511,
      EntityId: 1002,
      EntityName: "Activity",
      Slug: "sınırsız-gunluk-freeride-kayak-gezileri",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4512,
      EntityId: 1013,
      EntityName: "SkiResort",
      Slug: "ovit-mountain",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4513,
      EntityId: 1017,
      EntityName: "Hotel",
      Slug: "sarıkamıs-kayı-resort-otel-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4514,
      EntityId: 1062,
      EntityName: "Room",
      Slug: "sway-hotel-palandoken-3-sway-hotel-palandoken-oda-1",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4515,
      EntityId: 1062,
      EntityName: "Room",
      Slug: "sway-hotel-palandoken-3-standart-oda",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4516,
      EntityId: 1063,
      EntityName: "Room",
      Slug: "sway-hotel-palandoken-3-deluxe-oda",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4517,
      EntityId: 1064,
      EntityName: "Room",
      Slug: "sway-hotel-palandoken-3-family-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4518,
      EntityId: 1063,
      EntityName: "Room",
      Slug: "sway-hotel-palandoken-3-deluxe-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4519,
      EntityId: 1062,
      EntityName: "Room",
      Slug: "sway-hotel-palandoken-3-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4520,
      EntityId: 1065,
      EntityName: "Room",
      Slug: "sway-hotel-palandoken-3-junior-suit",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4541,
      EntityId: 3,
      EntityName: "Hotel",
      Slug: "dorukkaya-ski-resort-kartalkaya",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4543,
      EntityId: 1044,
      EntityName: "Room",
      Slug: "dorukkaya-ski-resort-kartalkaya-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4544,
      EntityId: 1066,
      EntityName: "Room",
      Slug: "radisson-blu-hotel-3-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4545,
      EntityId: 1067,
      EntityName: "Room",
      Slug: "radisson-blu-hotel-3-double-room-premium-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4546,
      EntityId: 1068,
      EntityName: "Room",
      Slug: "radisson-blu-hotel-3-triple-room-executive-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4547,
      EntityId: 1069,
      EntityName: "Room",
      Slug: "mirada-del-lago-otel-2-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4548,
      EntityId: 1070,
      EntityName: "Room",
      Slug: "mirada-del-lago-otel-2-king-apartment-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4549,
      EntityId: 1071,
      EntityName: "Room",
      Slug: "mirada-del-lago-otel-2-grand-suit",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4550,
      EntityId: 3,
      EntityName: "Hotel",
      Slug: "dorukkaya-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4551,
      EntityId: 1072,
      EntityName: "Room",
      Slug: "dorukkaya-ski-resort-family-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4552,
      EntityId: 1073,
      EntityName: "Room",
      Slug: "dorukkaya-ski-resort-superior-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4553,
      EntityId: 1074,
      EntityName: "Room",
      Slug: "dorukkaya-ski-resort-grand-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4554,
      EntityId: 1019,
      EntityName: "Room",
      Slug: "4-kisilik-oda",
      IsActive: 0,
      LanguageId: 1,
    },
    {
      Id: 4555,
      EntityId: 3,
      EntityName: "SkiResort",
      Slug: "erciyes-ski-resort-turkey",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4556,
      EntityId: 11,
      EntityName: "Hotel",
      Slug: "snowdora-hotel-palandoken-ejder-3200",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4557,
      EntityId: 1005,
      EntityName: "Room",
      Slug: "palan-hotel-trible-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4558,
      EntityId: 1006,
      EntityName: "Room",
      Slug: "palan-hotel-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4559,
      EntityId: 5,
      EntityName: "SkiResort",
      Slug: "palandoken-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4560,
      EntityId: 1023,
      EntityName: "Hotel",
      Slug: "sway-hotel-palandoken-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4561,
      EntityId: 13,
      EntityName: "Hotel",
      Slug: "dedeman-hotel-palandoken",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4562,
      EntityId: 1007,
      EntityName: "Room",
      Slug: "dedeman-hotel-palandoken-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4563,
      EntityId: 1008,
      EntityName: "Room",
      Slug: "dedeman-hotel-palandoken-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4564,
      EntityId: 1009,
      EntityName: "Room",
      Slug: "dedeman-hotel-palandoken-triple-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4565,
      EntityId: 1010,
      EntityName: "Room",
      Slug: "dedeman-hotel-palandoken-deluxe-trible-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4566,
      EntityId: 1024,
      EntityName: "Hotel",
      Slug: "sway-hotel-palandoken-3",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4567,
      EntityId: 1013,
      EntityName: "Hotel",
      Slug: "mirada-del-lago-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4568,
      EntityId: 1075,
      EntityName: "Room",
      Slug: "mirada-del-lago-hotel-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4569,
      EntityId: 1076,
      EntityName: "Room",
      Slug: "mirada-del-lago-hotel-room-for-disabled",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4570,
      EntityId: 1076,
      EntityName: "Room",
      Slug: "mirada-del-lago-hotel-romm-for-disabled",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4571,
      EntityId: 1077,
      EntityName: "Room",
      Slug: "mirada-del-lago-hotel-family-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4572,
      EntityId: 1002,
      EntityName: "Room",
      Slug: "snowdora-hotel-palandoken-ejder-3200-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4573,
      EntityId: 1078,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-standart-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4574,
      EntityId: 1079,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-family-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4575,
      EntityId: 1080,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-connection-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4576,
      EntityId: 1081,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-corner-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4577,
      EntityId: 1082,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-junior-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4578,
      EntityId: 1083,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-king-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4579,
      EntityId: 1084,
      EntityName: "Room",
      Slug: "bof-otel-uludag-standard-trible-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4580,
      EntityId: 1085,
      EntityName: "Room",
      Slug: "bof-otel-uludag-single-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4581,
      EntityId: 1086,
      EntityName: "Room",
      Slug: "bof-otel-uludag-standart-dbl-room",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4582,
      EntityId: 1086,
      EntityName: "Room",
      Slug: "bof-otel-uludag-standart-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4583,
      EntityId: 1087,
      EntityName: "Room",
      Slug: "bof-otel-uludag-junior-suite",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4584,
      EntityId: 15,
      EntityName: "Hotel",
      Slug: "sarıkamıs-kayı-resort-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4585,
      EntityId: 1057,
      EntityName: "Room",
      Slug: "sarıkamıs-kayı-resort-hotel-standard-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4586,
      EntityId: 1002,
      EntityName: "SkiSchool",
      Slug: "palandoken-kayak-okulu",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4587,
      EntityId: 1004,
      EntityName: "SkiSchool",
      Slug: "kartal-kaya-ski-school",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4588,
      EntityId: 1005,
      EntityName: "SkiSchool",
      Slug: "uludag-ski-school",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4589,
      EntityId: 1006,
      EntityName: "SkiSchool",
      Slug: "erciyes-ski-school",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4711,
      EntityId: 1,
      EntityName: "Tour",
      Slug: "kartalkaya-acılıs-turları-10-18-aralık-19-29-aralık-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4712,
      EntityId: 8,
      EntityName: "Tour",
      Slug: "palandoken-kayak-tatili-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4713,
      EntityId: 10,
      EntityName: "Tour",
      Slug: "sarıkamıs-kayak-tatili-1-30-aralık-acılıs-programı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4714,
      EntityId: 11,
      EntityName: "Tour",
      Slug: "uludag-kayak-egitimi-kampları-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4715,
      EntityId: 12,
      EntityName: "Tour",
      Slug: "haftasonu-erciyes-kayak-turu-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4716,
      EntityId: 13,
      EntityName: "Tour",
      Slug:
        "doguyu-kesif-gezileri-3-farklı-kayak-merkezi-palandoken-konakli-sarikamis-turu-2021",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4717,
      EntityId: 15,
      EntityName: "Tour",
      Slug: "yılbası-palandoken-kayak-turu-aile-paketi-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4718,
      EntityId: 16,
      EntityName: "Tour",
      Slug:
        "okullara-ozel-kayak-egitim-kampları-2-gece-3-gunduz-grand-kartal-konaklamali-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4719,
      EntityId: 9,
      EntityName: "Tour",
      Slug: "palandoken-haftasonu-turları-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4720,
      EntityId: 17,
      EntityName: "Tour",
      Slug: "yılbası-gudauri-2021-sezon-acılısı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4721,
      EntityId: 19,
      EntityName: "Tour",
      Slug:
        "7-10-mart-kartalkaya-unique-weekend-ankara-tesvik-kayak-ve-snowboard-alp-disiplini-ve-freestyle-yarısmaları-jazz-festivali",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4722,
      EntityId: 14,
      EntityName: "Tour",
      Slug: "gunubirlik-haftasonu-kartalkaya-dorukkaya-pistleri-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4723,
      EntityId: 18,
      EntityName: "Tour",
      Slug:
        "gurcistan-gudauri-kayak-ve-snowboard-turları-freeride-ve-back-country-isteyenlere-214zel-2020",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4724,
      EntityId: 20,
      EntityName: "Tour",
      Slug:
        "Istanbul-dan-haftasonu-erciyes-turları-amp-kisiye-214zel-kayak-egitim-kampları",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4725,
      EntityId: 20,
      EntityName: "Tour",
      Slug:
        "Istanbul-dan-haftasonu-erciyes-turları-kisiye-ozel-kayak-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4726,
      EntityId: 56,
      EntityName: "Tour",
      Slug: "bansko-kayak-egitim-paketleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4727,
      EntityId: 21,
      EntityName: "Tour",
      Slug: "gunubirlik-kartalkaya-kayak-turu-2021-2022",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4728,
      EntityId: 22,
      EntityName: "Tour",
      Slug: "icefest-palandoken-12-15-march-15-18-march",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4729,
      EntityId: 24,
      EntityName: "Tour",
      Slug: "20-23-aralık-christmas-kartalkaya-tatili-3-gece-4-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4730,
      EntityId: 25,
      EntityName: "Tour",
      Slug:
        "sarıkamıs-kayak-turu-ve-kayak-egitim-kampı-18-22-ocak-tam-pansiyon-paket-program",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4731,
      EntityId: 23,
      EntityName: "Tour",
      Slug:
        "2020-sezon-kapanıs-kartalkaya-haftasonu-organizasyonu-14-mart-cumartesi-veya-15-mart-pazar-konaklamalı",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4732,
      EntityId: 29,
      EntityName: "Tour",
      Slug: "somestr-Italya-alplerinde-kayak-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4733,
      EntityId: 28,
      EntityName: "Tour",
      Slug: "bansko-20-2020-99-eurodan-baslayan-fiyatlarla",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4734,
      EntityId: 30,
      EntityName: "Tour",
      Slug: "2018-2019-somestr-donemi-Italya-alplerinde-kayak-turu",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4735,
      EntityId: 31,
      EntityName: "Tour",
      Slug: "gunubirlik-kartalkaya-kayakampsnowboard-antremanı",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4736,
      EntityId: 32,
      EntityName: "Tour",
      Slug: "valdisere-fransa-alpleri-kayak-tatili-2020",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4737,
      EntityId: 33,
      EntityName: "Tour",
      Slug: "avusturya-alpleri-solden-somestr-kayak-egitim-paketleri-2019",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4738,
      EntityId: 34,
      EntityName: "Tour",
      Slug: "rusya-elbruz-4100-metre-freeride-ve-backcountry-programı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4739,
      EntityId: 35,
      EntityName: "Tour",
      Slug:
        "26-ocak-2-subat-2020-amp-2-subat-9-subat-valdisere-1-hafta-alplerde-kayak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4740,
      EntityId: 36,
      EntityName: "Tour",
      Slug: "ischgl-innsbruck-somestr-kayak-turu-27-ocak-3-subat-895-euro",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4741,
      EntityId: 37,
      EntityName: "Tour",
      Slug: "innsbruck-avusturya-alperi-sezon-boyunca-her-hafta",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4742,
      EntityId: 39,
      EntityName: "Tour",
      Slug: "golden-key-kartalkaya-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4743,
      EntityId: 40,
      EntityName: "Tour",
      Slug: "uslan-otel-uludag",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4744,
      EntityId: 41,
      EntityName: "Tour",
      Slug: "grand-yazıcı-otel-uludag",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4745,
      EntityId: 42,
      EntityName: "Tour",
      Slug: "grand-toprak-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4746,
      EntityId: 43,
      EntityName: "Tour",
      Slug: "erzurum-palan-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4747,
      EntityId: 44,
      EntityName: "Tour",
      Slug: "dedeman-ski-lounge-palandoken-2019",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4748,
      EntityId: 47,
      EntityName: "Tour",
      Slug: "fis-snowboard-world-cup-2-4-mart",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4749,
      EntityId: 48,
      EntityName: "Tour",
      Slug: "erciyes-haftasonu-turları-kisiye-214zel-kayak-egitim-kampları",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4750,
      EntityId: 45,
      EntityName: "Tour",
      Slug: "haftasonu-grup-egitimleri-erciyes-23-25-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4751,
      EntityId: 46,
      EntityName: "Tour",
      Slug:
        "2020-club-med-ile-1-hafta-hersey-dahil-fransa-Isvicre-Italya-alpleri-on-kayıt-ile-en-iyi-fiyat-garantisi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4752,
      EntityId: 49,
      EntityName: "Tour",
      Slug: "rusya-dombay-kayak-tatili-4-gece-6-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4753,
      EntityId: 50,
      EntityName: "Tour",
      Slug: "hafta-ici-konaklamalı-kartal-otel-amp-grand-kartal-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4754,
      EntityId: 52,
      EntityName: "Tour",
      Slug: "stubaital-kayak-tatili-4-8-nisan-sezon-kapanısı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4755,
      EntityId: 53,
      EntityName: "Tour",
      Slug:
        "avusturya-kayak-turları-paznaun-kayak-koyleri-Ischgl-galtur-kappi-ve-see-13-18-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4756,
      EntityId: 55,
      EntityName: "Tour",
      Slug: "ucak-ile-bansko-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4757,
      EntityId: 60,
      EntityName: "Tour",
      Slug:
        "somestr-erciyes-egitim-kampı-ve-kayak-tatili-27-ocak-2-subat-6-gece-7-gun-egitim-paketi-1510-tl",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4758,
      EntityId: 61,
      EntityName: "Tour",
      Slug: "kartalkaya-haftasonu-grup-snowboard-egitim-paketi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4759,
      EntityId: 51,
      EntityName: "Tour",
      Slug: "yunanistan-paranasos-kayak-turu",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4760,
      EntityId: 75,
      EntityName: "Tour",
      Slug: "haftasonu-Istanbul-ve-ankara-dan-kayseri-erciyes-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4761,
      EntityId: 76,
      EntityName: "Tour",
      Slug:
        "kartalkaya-christmas-tatiline-214zel-fiyatlar-ile-24-27-aralık-tatili-ve-egitim-kampı",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4762,
      EntityId: 54,
      EntityName: "Tour",
      Slug:
        "avusturya-kayak-turları-paznaun-kayak-koyleri-Ischgl-galtur-kappi-ve-see-13-18-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4763,
      EntityId: 77,
      EntityName: "Tour",
      Slug: "4-8-subat-ukrayna-bukovel-vizesiz-kayak-ve-snowboard-turu-2017",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4764,
      EntityId: 78,
      EntityName: "Tour",
      Slug: "somestr-donemi-gurcistan-gudauri-programı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4765,
      EntityId: 79,
      EntityName: "Tour",
      Slug:
        "2018-kıs-sezonu-kapanıs-turu-gurcistan-gudauri-vize-yok-pasaport-yok-480-",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4766,
      EntityId: 57,
      EntityName: "Tour",
      Slug: "zermatt-kayak-turu-10-17-subat-7-gece-8-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4767,
      EntityId: 58,
      EntityName: "Tour",
      Slug:
        "Isvicre-kayak-turu-ciftlere-ozel-sevgililer-gunu-programı-14-18-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4768,
      EntityId: 59,
      EntityName: "Tour",
      Slug:
        "club-med-ile-1-hafta-hersey-dahil-fransa-Isvicre-Italya-alpleri-214n-kayıt-ile-en-iyi-fiyat-garantisi",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4769,
      EntityId: 62,
      EntityName: "Tour",
      Slug:
        "kartalkaya-gunubirlik-kayak-turu-erken-rezervasyon-kampanyası-kayak-kirası-dahil",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4770,
      EntityId: 63,
      EntityName: "Tour",
      Slug:
        "Italya-aile-tatili-2439-eurodan-baslayan-fiyatlarla-5-gece-6-gun-somestr-donemi-29-ocak-3-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4771,
      EntityId: 65,
      EntityName: "Tour",
      Slug: "yetiskinlere-grup-kayak-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4772,
      EntityId: 66,
      EntityName: "Tour",
      Slug: "25-27-subat-sarkamıs-kayak-turu",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4773,
      EntityId: 67,
      EntityName: "Tour",
      Slug: "bof-hotel-uludag-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4774,
      EntityId: 68,
      EntityName: "Tour",
      Slug: "mirada-del-lago-hotel-erciyes",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4775,
      EntityId: 69,
      EntityName: "Tour",
      Slug: "mirada-del-monte-erciyes",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4776,
      EntityId: 70,
      EntityName: "Tour",
      Slug: "polat-hotel-palandoken",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4777,
      EntityId: 73,
      EntityName: "Tour",
      Slug: "uludag-kayak-merkezi-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4778,
      EntityId: 74,
      EntityName: "Tour",
      Slug: "avusturya-alplerinde-kayak-sezonunu-acıyoruz",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4779,
      EntityId: 64,
      EntityName: "Tour",
      Slug:
        "yılbası-kapadokyaamperciyes-kayak-turu-aile-paketi-29-aralık-2-ocak-yarım-pansiyon-paket-program",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4780,
      EntityId: 92,
      EntityName: "Tour",
      Slug: "hotel-kitzhof-resort-kitzbuhel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4781,
      EntityId: 72,
      EntityName: "Tour",
      Slug: "bildik-otel-sarıkamıs",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4782,
      EntityId: 80,
      EntityName: "Tour",
      Slug: "bansko-kayak-egItIm-kamplari",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4783,
      EntityId: 82,
      EntityName: "Tour",
      Slug: "pamporovo-kayak-turu-129-eurodan-baslayan-fiyatlarla",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4784,
      EntityId: 81,
      EntityName: "Tour",
      Slug: "pamporovo-kayak-egItIm-kamplari",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4785,
      EntityId: 83,
      EntityName: "Tour",
      Slug:
        "valdi-fass-kayak-merkezi-moena-Italyan-turk-kasabası-konaklamalı-30-ocak-6-subat-6-gece-7gun-799-euro",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4786,
      EntityId: 84,
      EntityName: "Tour",
      Slug:
        "Italya-alplerine-bir-yolculuk-trentino-fiemme-vallewiva-31-ocak-5-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4787,
      EntityId: 85,
      EntityName: "Tour",
      Slug:
        "somestr-donemi-erciyes-egitim-kampı-somestr-donemi-3-gece-4-gunluk-paketler",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4788,
      EntityId: 86,
      EntityName: "Tour",
      Slug:
        "somestr-donemi-alp-daglarına-fransa-bella-la-plagne-bolgesi-29-ocak-5-subat-1-hafta-somestr-kayak-tatili",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4789,
      EntityId: 88,
      EntityName: "Tour",
      Slug:
        "somestr-donemi-alp-daglarına-avusturya-salzburg-kayak-ve-snowboard-turu",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4790,
      EntityId: 89,
      EntityName: "Tour",
      Slug: "bansko-kayak-turu-tum-sezon-boyunca",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4791,
      EntityId: 94,
      EntityName: "Tour",
      Slug: "camkar-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4792,
      EntityId: 95,
      EntityName: "Tour",
      Slug: "dedeman-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4793,
      EntityId: 96,
      EntityName: "Tour",
      Slug: "ibis-hotel-kayseri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4794,
      EntityId: 99,
      EntityName: "Tour",
      Slug: "novotel-kayseri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4795,
      EntityId: 102,
      EntityName: "Tour",
      Slug: "2018-2019-somestr-kayak-ve-snowboard-egitim-kampları-3-gece-4-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4796,
      EntityId: 103,
      EntityName: "Tour",
      Slug:
        "kartalkaya-sezon-acılısı-22-23-aralık-haftasonu-kartalkaya-kayak-tatili",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4797,
      EntityId: 104,
      EntityName: "Tour",
      Slug:
        "2018-2019-kartalkaya-somestr-kayak-ve-snowboard-egitim-kampları-2-gece-3-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4798,
      EntityId: 105,
      EntityName: "Tour",
      Slug: "2019-chirstmas-egitim-kampı-kartalkaya",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4799,
      EntityId: 87,
      EntityName: "Tour",
      Slug: "bilkent-universitesi-kayak-kulubu-bansko-programı-24-30-ocak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4800,
      EntityId: 106,
      EntityName: "Tour",
      Slug:
        "8-10-subat-uludag-haftasonu-kayak-turu-ampuludag-kayak-egitim-kampı-2019",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4801,
      EntityId: 91,
      EntityName: "Tour",
      Slug: "2-7-subat-livigno-Italya-kayak-ve-snowboard-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4802,
      EntityId: 93,
      EntityName: "Tour",
      Slug: "gombit-hotel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4803,
      EntityId: 97,
      EntityName: "Tour",
      Slug: "pension-kirchplatz-st-anton-am-arlberg",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4804,
      EntityId: 98,
      EntityName: "Tour",
      Slug: "Ibis-hotel-kayseri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4805,
      EntityId: 100,
      EntityName: "Tour",
      Slug: "pazar-tek-gece-konaklamalı-248-tlden-baslayan-fiyatlarla",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4806,
      EntityId: 101,
      EntityName: "Tour",
      Slug:
        "2018-2019-stubai-snowpark-sezon-acılısı-avusturya-stubai-zoo-18-ekim-22-ekim",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4807,
      EntityId: 107,
      EntityName: "Tour",
      Slug:
        "2019-yılbası-kayak-tatili-29-aralık-1-ocak-kayseri-erciyes-kapadokya",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4808,
      EntityId: 108,
      EntityName: "Tour",
      Slug: "2018-chirstmas-egitim-kampı-erciyes",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4809,
      EntityId: 109,
      EntityName: "Tour",
      Slug: "2018-2019-somestr-kayak-ve-snowboard-egitim-kampları-3-gece-4-gun",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4810,
      EntityId: 110,
      EntityName: "Tour",
      Slug: "2019-sezon-acilisi-yilbasi-bansko-29-aralik-1-ocak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4811,
      EntityId: 111,
      EntityName: "Tour",
      Slug:
        "2016-2017-kis-sezonu-solden-kapanis-turu-ve-mountion-electric-festival-5-10-nisan",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4812,
      EntityId: 112,
      EntityName: "Tour",
      Slug:
        "30-kasım-5-aralık-2019-sezon-acılısı-les-deux-alpes-fransa-buzulları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4813,
      EntityId: 113,
      EntityName: "Tour",
      Slug:
        "2018-2019-kayak-sezonu-haftasonu-acılıs-etkinligi-1-2-aralık-sway-hotel-konaklamalı-palandoken",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4814,
      EntityId: 116,
      EntityName: "Tour",
      Slug:
        "yılbası-kartalkaya-kayak-turu-aile-paketi-29-aralık-2-ocak-hersey-dahil-paket-program",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4815,
      EntityId: 117,
      EntityName: "Tour",
      Slug: "2018-sezonu-kapanısı-bansko-31-mart-3-nisan",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4816,
      EntityId: 120,
      EntityName: "Tour",
      Slug: "Italya-kayak-turu-20-24-ocak-2018",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4817,
      EntityId: 121,
      EntityName: "Tour",
      Slug: "Italya-kayak-turu-icefest-genclik-festivali-20-26-ocak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4818,
      EntityId: 122,
      EntityName: "Tour",
      Slug: "6-ocak-11-ocak-Isvicre-crans-montana-kayak-merkezi-5-gece-6-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4819,
      EntityId: 123,
      EntityName: "Tour",
      Slug: "icefest-gudauri-22-26-ocak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4820,
      EntityId: 124,
      EntityName: "Tour",
      Slug:
        "Istanbul-ve-ankaradan-haftasonu-gunubirlik-kartalkaya-turları-kayak-kiralama-dahil",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4821,
      EntityId: 125,
      EntityName: "Tour",
      Slug: "val-disere-sezon-acılıs-organizasyonu-1-aralık-9-aralık-2017",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4822,
      EntityId: 114,
      EntityName: "Tour",
      Slug: "kayak-merkezi-transferleri-yurtici",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4823,
      EntityId: 115,
      EntityName: "Tour",
      Slug:
        "yılbası-kayseri-radisson-blu-kalmalı-erciyes-yılbası-programı-30-aralık-1-ocak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4824,
      EntityId: 118,
      EntityName: "Tour",
      Slug:
        "yılbası-erciyes-kayak-turu-aile-paketi-29-aralık-2-ocak-tam-pansiyon-plus-paket-program",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4825,
      EntityId: 119,
      EntityName: "Tour",
      Slug:
        "yılbası-uludag-kayak-turu-aile-paketi-29-aralık-2-ocak-tam-pansiyon-paket-program",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4826,
      EntityId: 126,
      EntityName: "Tour",
      Slug: "yurtdısı-kayak-merkezI-transferleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4827,
      EntityId: 76,
      EntityName: "Tour",
      Slug:
        "kartalkaya-christmas-tatiline-ozel-fiyatlar-ile-24-27-aralık-tatili-ve-egitim-kampı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4828,
      EntityId: 48,
      EntityName: "Tour",
      Slug: "erciyes-haftasonu-turları-kisiye-ozel-kayak-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4829,
      EntityId: 59,
      EntityName: "Tour",
      Slug:
        "club-med-ile-1-hafta-hersey-dahil-fransa-Isvicre-Italya-alpleri-on-kayıt-ile-en-iyi-fiyat-garantisi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4830,
      EntityId: 106,
      EntityName: "Tour",
      Slug:
        "8-10-subat-uludag-haftasonu-kayak-turu-uludag-kayak-egitim-kampı-2019",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4831,
      EntityId: 18,
      EntityName: "Tour",
      Slug:
        "gurcistan-gudauri-kayak-ve-snowboard-turları-freeride-ve-back-country-isteyenlere-ozel-2020",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4832,
      EntityId: 31,
      EntityName: "Tour",
      Slug: "gunubirlik-kartalkaya-kayak-snowboard-antremanı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4833,
      EntityId: 1088,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-denemeotel1",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4834,
      EntityId: 1089,
      EntityName: "Room",
      Slug: "grand-yazıcı-uludag-2-deneme-otel",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4835,
      EntityId: 1008,
      EntityName: "Restaurant",
      Slug: "cafe-kartal",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4836,
      EntityId: 1008,
      EntityName: "Restaurant",
      Slug: "cafe-kartal",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4837,
      EntityId: 1008,
      EntityName: "Restaurant",
      Slug: "cafe-kartal",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4838,
      EntityId: 4,
      EntityName: "TourCategory",
      Slug: "2019-kayak-turları",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4839,
      EntityId: 3,
      EntityName: "TourCategory",
      Slug: "2020-kayak-turları",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4840,
      EntityId: 15,
      EntityName: "TourCategory",
      Slug: "2021-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4841,
      EntityId: 13,
      EntityName: "TourCategory",
      Slug: "kayak-merkezi-transferleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4842,
      EntityId: 5,
      EntityName: "TourCategory",
      Slug: "somestr-tatili-kayak-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4843,
      EntityId: 7,
      EntityName: "TourCategory",
      Slug: "yurt-ici-kayak-ve-snowboard-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4844,
      EntityId: 9,
      EntityName: "TourCategory",
      Slug: "yurt-ici-kayak-ve-snowboard-egitimleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4845,
      EntityId: 11,
      EntityName: "TourCategory",
      Slug: "yurt-ici-kayak-otelleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4846,
      EntityId: 8,
      EntityName: "TourCategory",
      Slug: "yurt-dısı-kayak-ve-snowboard-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4847,
      EntityId: 10,
      EntityName: "TourCategory",
      Slug: "yurt-dısı-kayak-ve-snowboard-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4848,
      EntityId: 12,
      EntityName: "TourCategory",
      Slug: "yurt-dısı-kayak-otelleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4849,
      EntityId: 6,
      EntityName: "TourCategory",
      Slug: "yılbası-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4850,
      EntityId: 14,
      EntityName: "TourCategory",
      Slug: "vizesiz-yurt-dısı-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4851,
      EntityId: 62,
      EntityName: "TourCategory",
      Slug: "haftasonu-erciyes-kayak-turu-2021-2022-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4852,
      EntityId: 61,
      EntityName: "TourCategory",
      Slug:
        "club-med-ile-1-hafta-hersey-dahil-fransa-Isvicre-Italya-alpleri-on-kayıt-ile-en-iyi-fiyat-garantisi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4853,
      EntityId: 60,
      EntityName: "TourCategory",
      Slug: "bansko-kayak-egitim-paketleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4854,
      EntityId: 56,
      EntityName: "TourCategory",
      Slug:
        "26-ocak-2-subat-2020-2-subat-9-subat-valdisere-1-hafta-alplerde-kayak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4855,
      EntityId: 59,
      EntityName: "TourCategory",
      Slug:
        "2020-club-med-ile-1-hafta-hersey-dahil-fransa-Isvicre-Italya-alpleri-on-kayıt-ile-en-iyi-fiyat-garantisi",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4856,
      EntityId: 58,
      EntityName: "TourCategory",
      Slug: "2018-2019-somestr-donemi-Italya-alplerinde-kayak-turu",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4857,
      EntityId: 57,
      EntityName: "TourCategory",
      Slug: "2018-2019-somestr-kayak-ve-snowboard-egitim-kampları-3-gece-4-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4858,
      EntityId: 63,
      EntityName: "TourCategory",
      Slug: "haftasonu-grup-egitimleri-erciyes-23-25-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4859,
      EntityId: 64,
      EntityName: "TourCategory",
      Slug: "innsbruck-avusturya-alperi-sezon-boyunca-her-hafta-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4860,
      EntityId: 65,
      EntityName: "TourCategory",
      Slug: "innsbruck-avusturya-alpleri-somestr-kayak-turları-23-ocak-30-ocak",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4861,
      EntityId: 66,
      EntityName: "TourCategory",
      Slug: "ischgl-innsbruck-somestr-kayak-turu-27-ocak-3-subat-895-euro",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4862,
      EntityId: 67,
      EntityName: "TourCategory",
      Slug:
        "Istanbul-dan-haftasonu-erciyes-turları-kisiye-ozel-kayak-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4863,
      EntityId: 68,
      EntityName: "TourCategory",
      Slug:
        "Italya-aile-tatili-2439-eurodan-baslayan-fiyatlarla-5-gece-6-gun-somestr-donemi-29-ocak-3-subat",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4864,
      EntityId: 69,
      EntityName: "TourCategory",
      Slug: "palandoken-kayak-tatili-2021-2022-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4865,
      EntityId: 70,
      EntityName: "TourCategory",
      Slug: "somestr-donemi-gurcistan-gudauri-programı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4866,
      EntityId: 71,
      EntityName: "TourCategory",
      Slug: "somestr-Italya-alplerinde-kayak-egitim-kampları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4867,
      EntityId: 72,
      EntityName: "TourCategory",
      Slug: "stubaital-kayak-tatili-4-8-nisan-sezon-kapanısı",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4868,
      EntityId: 73,
      EntityName: "TourCategory",
      Slug: "uludag-kayak-egitimi-kampları-2021-2022",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4869,
      EntityId: 74,
      EntityName: "TourCategory",
      Slug: "valdisere-fransa-alpleri-kayak-tatili-2020-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4870,
      EntityId: 75,
      EntityName: "TourCategory",
      Slug: "zermatt-kayak-turu-10-17-subat-7-gece-8-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4871,
      EntityId: 23,
      EntityName: "TourCategory",
      Slug: "avusturya-turları-ydkst",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4872,
      EntityId: 24,
      EntityName: "TourCategory",
      Slug: "fransa-kayak-turları-ydkst",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4873,
      EntityId: 25,
      EntityName: "TourCategory",
      Slug: "gurcistan-kayak-turları-ydkst",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4874,
      EntityId: 26,
      EntityName: "TourCategory",
      Slug: "Isvicre-kayak-turları-ydkst",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4875,
      EntityId: 27,
      EntityName: "TourCategory",
      Slug: "Italya-turları-ydkst",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4876,
      EntityId: 29,
      EntityName: "TourCategory",
      Slug: "otobus-ile-bansko-4-gece-5-gun-ydkst",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4877,
      EntityId: 28,
      EntityName: "TourCategory",
      Slug: "otobus-ile-bansko-3-gece-4-gun-ydkst",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4878,
      EntityId: 49,
      EntityName: "TourCategory",
      Slug: "haftasonu-erciyes-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4879,
      EntityId: 48,
      EntityName: "TourCategory",
      Slug: "gunubirlik-turlar",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4880,
      EntityId: 47,
      EntityName: "TourCategory",
      Slug: "uludag",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4881,
      EntityId: 46,
      EntityName: "TourCategory",
      Slug: "sarıkamıs",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4882,
      EntityId: 45,
      EntityName: "TourCategory",
      Slug: "palandoken",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4883,
      EntityId: 44,
      EntityName: "TourCategory",
      Slug: "kartalkaya",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4884,
      EntityId: 43,
      EntityName: "TourCategory",
      Slug: "erken-rezervasyon-otelleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4885,
      EntityId: 42,
      EntityName: "TourCategory",
      Slug: "erciyes",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4886,
      EntityId: 35,
      EntityName: "TourCategory",
      Slug: "yunanistan-paranasos-kayak-turu-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4887,
      EntityId: 34,
      EntityName: "TourCategory",
      Slug: "ukrayna-bukovel-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4888,
      EntityId: 33,
      EntityName: "TourCategory",
      Slug: "rusya-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4889,
      EntityId: 32,
      EntityName: "TourCategory",
      Slug: "pamporovo-kayak-turu",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4890,
      EntityId: 31,
      EntityName: "TourCategory",
      Slug: "otobus-ile-bansko-7-gece-8-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4891,
      EntityId: 30,
      EntityName: "TourCategory",
      Slug: "otobus-ile-bansko-5-gece-6-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4892,
      EntityId: 41,
      EntityName: "TourCategory",
      Slug: "italya",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4893,
      EntityId: 40,
      EntityName: "TourCategory",
      Slug: "Isvicre",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4894,
      EntityId: 39,
      EntityName: "TourCategory",
      Slug: "gurcistan-gudauri-otelleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4895,
      EntityId: 38,
      EntityName: "TourCategory",
      Slug: "fransa",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4896,
      EntityId: 37,
      EntityName: "TourCategory",
      Slug: "bansko-otelleri",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4897,
      EntityId: 36,
      EntityName: "TourCategory",
      Slug: "avusturya",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4898,
      EntityId: 55,
      EntityName: "TourCategory",
      Slug: "yılbası-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4899,
      EntityId: 54,
      EntityName: "TourCategory",
      Slug: "uludag-hafta-sonu-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4900,
      EntityId: 53,
      EntityName: "TourCategory",
      Slug: "sarıkamıs-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4901,
      EntityId: 52,
      EntityName: "TourCategory",
      Slug: "palandokan-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4902,
      EntityId: 51,
      EntityName: "TourCategory",
      Slug: "kartalya-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4903,
      EntityId: 50,
      EntityName: "TourCategory",
      Slug: "haftasonu-kartalkaya-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4904,
      EntityId: 29,
      EntityName: "TourCategory",
      Slug: "otobus-ile-bansko-4-gece-5-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4905,
      EntityId: 28,
      EntityName: "TourCategory",
      Slug: "otobus-ile-bansko-3-gece-4-gun",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4906,
      EntityId: 27,
      EntityName: "TourCategory",
      Slug: "italya-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4907,
      EntityId: 26,
      EntityName: "TourCategory",
      Slug: "isvicre-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4908,
      EntityId: 25,
      EntityName: "TourCategory",
      Slug: "gurcistan-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4909,
      EntityId: 24,
      EntityName: "TourCategory",
      Slug: "fransa-kayak-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4910,
      EntityId: 23,
      EntityName: "TourCategory",
      Slug: "avusturya-turları",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4911,
      EntityId: 2,
      EntityName: "SkiResort",
      Slug: "uludag-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4912,
      EntityId: 73,
      EntityName: "TourCategory",
      Slug: "uludag-kayak-egitimi-kampları-2021-2022-2",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4913,
      EntityId: 34,
      EntityName: "Tour",
      Slug: "rusya-elbruz-4100-metre-programı",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4914,
      EntityId: 34,
      EntityName: "Tour",
      Slug: "rusya-elbruz-4100-metre-programı",
      IsActive: 0,
      LanguageId: 2,
    },
    {
      Id: 4915,
      EntityId: 34,
      EntityName: "Tour",
      Slug: "rusya-elbruz-4100-metre-freeride-ve-backcountry-programı",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4916,
      EntityId: 109,
      EntityName: "Tour",
      Slug:
        "2018-2019-somestr-kayak-ve-snowboard-egitim-kampları-3-gece-4-gun-1",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4917,
      EntityId: 127,
      EntityName: "Tour",
      Slug: "freefall-sportsmusic-festival-sarikamis-ski-resort",
      IsActive: 0,
      LanguageId: 0,
    },
    {
      Id: 4918,
      EntityId: 128,
      EntityName: "Tour",
      Slug:
        "ski-season-opening-palandoken-turkey-14th-15th-december-13th-15th-december",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4919,
      EntityId: 129,
      EntityName: "Tour",
      Slug: "christmas-ski-training-camp-family-package-24th-27th-december",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4920,
      EntityId: 130,
      EntityName: "Tour",
      Slug: "gudauri-ski-and-snowboard-new-year-ski-tour",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4921,
      EntityId: 136,
      EntityName: "Tour",
      Slug: "ski-training-camp-family-package-every-weekend",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4922,
      EntityId: 139,
      EntityName: "Tour",
      Slug: "palandoken-ski-holiday",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4923,
      EntityId: 146,
      EntityName: "Tour",
      Slug:
        "november-30th-december-5th-2019-france-glaciers-season-opening-les-deux-alpes-france-ski-tour",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4924,
      EntityId: 137,
      EntityName: "Tour",
      Slug: "uludag-ski-training-programmes",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4925,
      EntityId: 138,
      EntityName: "Tour",
      Slug: "erciyes-ski-holiday",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4926,
      EntityId: 140,
      EntityName: "Tour",
      Slug: "luxury-ski-holiday-in-turkey",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4927,
      EntityId: 141,
      EntityName: "Tour",
      Slug: "georgia-gudauri-freeride-ski-and-snowboard-tours",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4928,
      EntityId: 142,
      EntityName: "Tour",
      Slug: "palandoken-rb-ski-snowboarding-festival-turkey-13th-15th-march",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4929,
      EntityId: 143,
      EntityName: "Tour",
      Slug:
        "turkey-east-side-ski-expedition-palandoken-konaklı-sarıkamıs-total-track-length-is-103-km",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4930,
      EntityId: 144,
      EntityName: "Tour",
      Slug: "ski-music-festival-turkey",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4931,
      EntityId: 145,
      EntityName: "Tour",
      Slug: "sarikamis-ski-holiday",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4932,
      EntityId: 131,
      EntityName: "Tour",
      Slug: "serbia-kopaonik-semester-ski-tour",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4933,
      EntityId: 132,
      EntityName: "Tour",
      Slug:
        "serbia-kopaonik-semester-international-ski-tour-25-january-2-february-2020",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4934,
      EntityId: 133,
      EntityName: "Tour",
      Slug:
        "christmas-ski-training-camp-turkey-family-package-21th-24th-december",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4935,
      EntityId: 134,
      EntityName: "Tour",
      Slug:
        "weekend-ski-training-camp-turkey-kartalkaya-family-package-29thfebruary-1thmarch",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4936,
      EntityId: 135,
      EntityName: "Tour",
      Slug: "2020-palandoken-turkey-ski-training-camp-youth-ski-camp",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4937,
      EntityId: 1086,
      EntityName: "Room",
      Slug: "standart-room-bof-hotel-uludag",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4938,
      EntityId: 19,
      EntityName: "Tour",
      Slug:
        "7-10-mart-kartalkaya-unique-weekend-ankara-tesvik-kayak-ve-snowboard-alp-disiplini-ve-freestyle-yarismalari-jazz-festivali",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4939,
      EntityId: 23,
      EntityName: "Tour",
      Slug:
        "2020-sezon-kapanis-kartalkaya-haftasonu-organizasyonu-14-mart-cumartesi-veya-15-mart-pazar-konaklamali",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4940,
      EntityId: 41,
      EntityName: "Tour",
      Slug: "grand-yazici-otel-uludag",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4941,
      EntityId: 5,
      EntityName: "Page",
      Slug: "tours",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4942,
      EntityId: 2,
      EntityName: "Page",
      Slug: "ski-resort",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4943,
      EntityId: 3,
      EntityName: "Page",
      Slug: "hotels",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4944,
      EntityId: 6,
      EntityName: "Page",
      Slug: "ski-school",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4945,
      EntityId: 4,
      EntityName: "Page",
      Slug: "food-beverage",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4946,
      EntityId: 4,
      EntityName: "TourCategory",
      Slug: "2019-kayak-turlari",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4947,
      EntityId: 4,
      EntityName: "TourCategory",
      Slug: "2019-ski-tours",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4948,
      EntityId: 3,
      EntityName: "TourCategory",
      Slug: "2020-kayak-turlari",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4949,
      EntityId: 3,
      EntityName: "TourCategory",
      Slug: "2020-ski-tours",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4950,
      EntityId: 127,
      EntityName: "Tour",
      Slug: "freefall-sarikamis-ski-resort",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4951,
      EntityId: 127,
      EntityName: "Tour",
      Slug: "free-fall-sarikamis-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4952,
      EntityId: 1006,
      EntityName: "Restaurant",
      Slug: "grand-kartal-restaurantlari",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4953,
      EntityId: 1006,
      EntityName: "Restaurant",
      Slug: "grand-kartal-restaurantlari",
      IsActive: 1,
      LanguageId: 1,
    },
    {
      Id: 4954,
      EntityId: 127,
      EntityName: "Tour",
      Slug: "ride-and-jump-sportsmusic-festival-sarikamis-ski-resort",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4955,
      EntityId: 1027,
      EntityName: "Hotel",
      Slug: "iceberg-otel-sarikamis",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4956,
      EntityId: 1027,
      EntityName: "Hotel",
      Slug: "iceberg-hotel-sarikamis-ski-resort",
      IsActive: 1,
      LanguageId: 2,
    },
    {
      Id: 4957,
      EntityId: 1090,
      EntityName: "Room",
      Slug: "standart-oda-iceberg-otel-sarikamis",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4958,
      EntityId: 1028,
      EntityName: "Hotel",
      Slug: "snowflake-hotel-sarikamis",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4959,
      EntityId: 1091,
      EntityName: "Room",
      Slug: "snowflake-hotel-double-room",
      IsActive: 1,
      LanguageId: 0,
    },
    {
      Id: 4960,
      EntityId: 1028,
      EntityName: "Hotel",
      Slug: "snowflake-otel-sarikamis-kayak-merkezi",
      IsActive: 1,
      LanguageId: 1,
    },
  ],
  topMenuPages: [],
  footerMenuPages: [],
  bottomMenuPages: []
};

const navigationSlice = createSlice({
  name: "Navigation Slice",
  initialState,
  reducers: {
    setTopMenuPages: (state, action) => {
      state.topMenuPages = action.payload;
    },
    setFooterMenuPages: (state, action) => {
      state.footerMenuPages = action.payload;
    },
    setBottomMenuPages: (state, action) => {
      state.bottomMenuPages = action.payload;
    },
  },
});

export const { setTopMenuPages,setFooterMenuPages,setBottomMenuPages } = navigationSlice.actions;

export default navigationSlice.reducer;
